export const seoConfig = {
  default: {
    title: "Free AI Detector & AI Checker",
    description: "Ensure your content remains authentically human. DetectAi instantly analyzes text, documents, and media to flag AI-generated content with 99.8% accuracy.",
    metaTitle: "Free AI Detector & AI Checker | DetectAi",
    defaultTab: "text",
    heroHighlight: "AI Checker",
    placeholderText: "To check your content, type or paste it here and click on the button below..."
  },
  text: {
    title: "Accurate AI Text Checker",
    description: "Check essays, emails, and articles for ChatGPT, Claude, and Gemini generation. 99.8% accuracy on modern LLMs.",
    metaTitle: "AI Text Detector & ChatGPT Checker | DetectAi",
    defaultTab: "text",
    heroHighlight: "Text Checker",
    placeholderText: "Paste your essay, article, or email here to check for AI generation..."
  },
  image: {
    title: "Free AI Image Detector",
    description: "Spot fake AI-generated images from Midjourney, DALL-E 3, and Stable Diffusion instantly.",
    metaTitle: "AI Image Detector | Spot Midjourney & DALL-E Fakes",
    defaultTab: "upload",
    heroHighlight: "Image Detector",
    placeholderText: ""
  },
  audio: {
    title: "Deepfake Audio & Voice Detector",
    description: "Identify synthetic voices, AI clones, and deepfake audio files from ElevenLabs and Suno.",
    metaTitle: "AI Audio & Voice Deepfake Detector | DetectAi",
    defaultTab: "upload",
    heroHighlight: "Voice Detector",
    placeholderText: ""
  },
  video: {
    title: "AI Video Forensics Engine",
    description: "Detect AI-generated videos, face manipulations, and Sora deepfakes with advanced pixel-level forensic analysis.",
    metaTitle: "AI Video Deepfake Detector & Forensics | DetectAi",
    defaultTab: "upload",
    heroHighlight: "Video Engine",
    placeholderText: ""
  },
  chatgpt_detector_for_teachers: {
    title: "ChatGPT Detector for Teachers",
    description: "The most accurate AI text detector for educators. Check student essays and assignments for ChatGPT and Claude generation.",
    metaTitle: "Free ChatGPT Detector for Teachers & Students | DetectAi",
    defaultTab: "text",
    heroHighlight: "Educator Tool",
    placeholderText: "Paste student essays or assignments here to check for AI plagiarism..."
  },
  midjourney_image_checker: {
    title: "Midjourney & DALL-E Image Checker",
    description: "Identify fake AI-generated images. Our forensic image checker spots Midjourney, DALL-E 3, and Stable Diffusion fakes.",
    metaTitle: "Midjourney AI Image Checker & Fake Detector | DetectAi",
    defaultTab: "upload",
    heroHighlight: "Image Forensics",
    placeholderText: ""
  },
  sora_deepfake_detector: {
    title: "Sora & AI Video Deepfake Detector",
    description: "Scan videos for AI generation. Our video deepfake detector spots Sora, Runway, and AI-manipulated faces.",
    metaTitle: "Sora AI Video Deepfake Detector | DetectAi",
    defaultTab: "upload",
    heroHighlight: "Video Scanner",
    placeholderText: ""
  },
  detect_ai_generated_essay: {
    title: "Detect AI Generated Essays",
    description: "Instantly detect if an essay was written by an AI like ChatGPT, Claude, or Gemini. Free AI essay checker.",
    metaTitle: "Detect AI Generated Essays & Text | Free AI Checker",
    defaultTab: "text",
    heroHighlight: "Essay Checker",
    placeholderText: "Paste an essay here to see if it was written by AI..."
  },
  elevenlabs_voice_detector: {
    title: "ElevenLabs & AI Voice Detector",
    description: "Upload an audio file to detect synthetic voices, voice clones, and deepfake audio generated by ElevenLabs.",
    metaTitle: "ElevenLabs AI Voice & Deepfake Audio Detector",
    defaultTab: "upload",
    heroHighlight: "Voice Forensics",
    placeholderText: ""
  }
};
